[project]
name = "homage-server"
version = "0.1.0"
description = "a space to honor the projects i rely on"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.116.1",
    "pydantic-settings>=2.10.1",
    "surrealdb>=1.0.6",
]
